Modified heading structure to be more accurately read by screenreaders
department-of-veterans-affairs/caseflow-frontend-toolkit pull request #71
Opened 2021-04-05 14:53 UTC by mkerns355

Resolves [CASEFLOW-991](https://vajira.max.gov/browse/CASEFLOW-991)

### Description
Replaced the h1 tag for a p tag with exact styling used on h1 tags.

### Acceptance Criteria
- [] JAWS correctly reads Caseflow headings as intended.

### Testing Plan
1. Go to Case Details page.
2. Run JAWS.
3. Activate 'Headings' Mode.
4. Verify that JAWS reads the heading in the correct order.

2021-04-05 14:56 UTC, Jeremy1026 commented on components/NavigationBar.jsx
> +const pStyling = css({
Is `h1Styling` used anywhere else? Should `pStyling` be another style added with the additional `fontWeight` with `h1Styling` left as is?

2021-04-05 15:00 UTC, mkerns355 commented on components/NavigationBar.jsx
> +const pStyling = css({
Nope `h1Styling` isn't used anywhere else. I don't believe there needs to be any other style added. `h1Styling` can just be repurposed to match the elemental change.

2021-04-05 15:51 UTC, bgantick requested changes

2021-04-05 15:51 UTC, bgantick commented on components/NavigationBar.jsx
> +                  <p id="page-title" className="cf-application-title" {...STYLES.APPLICATION_TITLE}>
Might take the opportunity to correct the nesting of block level elements (nesting a `p` inside of a `p` isn't valid html)

2021-04-05 17:51 UTC, bgantick commented
@mkerns355 It looks like "Search cases" is heading lvl 3 within the header/nav. That should probably be corrected as well

2021-04-06 15:09 UTC, mkerns355 commented
> @mkerns355 It looks like "Search cases" is heading lvl 3 within the header/nav. That should probably be corrected as well (discovered when using headings mode in JAWS - reads "search cases" before moving to h1 in main body)

The Search is a component inside the Caseflow repo where I have already included the fix to the `h3`.

2021-04-06 15:11 UTC, bgantick approved these changes

2021-04-06 15:33 UTC, merged